Xolvez/DD2480-JavaScript

README.md

The template has been taken from [report.md](https://canvas.kth.se/courses/37918/files/6157559) given in the assignment.

Issue #4: Adds structure of report in Readme file

---

README.md

The README file is extended with information about the complexity of the function `BinaryToHex.hexLookup` and whether that complexity is appropriate or not. In addition to that it also includes a manual count of the cyclic complexity number.

Issue #7: Adds information to README file

---

README.md

Added a section about the onboarding experience and about how we switched between projects before we settled for one.

Issue #6: Write about the onboarding experience

---

README.md

The README file is extended with information about the complexity of the function `FlashSort.flashSort` and whether that complexity is appropriate or not. In addition to that it also includes a manual count of the cyclic complexity number.

Issue #8: Adds information to README file

---

README.md

The README file is extended with information about how the function `BinaryToHex.hexLookup` can be refactored in order to reduce its cyclic complexity number.

Issue #9: Adds information to README file

---

README.md

Constructed a refractoring plan for the integralEvaluation function and documented it in the README.

Issue #20: Write a refractoring plan for the integralEvaluation-function

---

README.md

The README file is extended with information and results from the implemented ad-hoc coverage tool for the function `FlashSort.flashSort`.

Issue #10: Adds information to README file

---

Conversions/BinaryToHex.js
README.md

Refactors the function `BinaryToHex.hexLookup` so that it performs the conversion through a computation rather than a lookup.

Issue #13: Refactors the function `BinaryToHex.hexLookup`

---

README.md
Sorts/test/FlashSort.test.js

Extends the testing with a case where the input array consists of multiple elements that are all of the same value and another case where the input array consists of the positive and negative extreme values for integers in descending order. Also updates the README file with the corresponding information.

Issue #12: Extends the testing of `FlashSort.flashSort`

---

.gitignore

Added the coverage directory to the .gitignore

Issue #45 Add the coverage directory to the .gitignore

---

README.md

Analysis of the complexity of `ConwaysGameOfLife.newGeneration`:
- purpose of the function
- CCN compared to NLOC and explained
- documentation of the different branches

Issue #32: Adds analysis of `ConwaysGameOfLife.newGeneration`

---

README.md

The README file is extended with information about the complexity of the function `RgbHsvConversion.getRgbBySection` and whether that complexity is appropriate or not.

Issue #26: Adds information to README file

---

README.md

The README file is extended with information about how the function `RgbHsvConversion.getRgbBySection` can be refactored in order to reduce its cyclic complexity number.

Issue #31: Adds information to README file

---

README.md

The README file is extended with information about the complexity of the function ConvexHullGraham.convexHull and whether that complexity is appropriate or not.

Issue #37: Adds information to README file

---

README.md

The README file is extended with information about how the function ConvexHullGraham.convexHull can be refactored in order to reduce its cyclic complexity number.

Issue #38: Adds information to README file

---

Geometry/ConvexHullGraham.js

Refactors the function ConvexHullGraham.convexHull.

Issue #39: Refactors the function ConvexHullGraham.convexHull

---

Conversions/RgbHsvConversion.js

Refactors the function RgbHsvConversion.getRgbBySection by optimizing the if-else branches.

Issue #34: Refactors the function RgbHsvConversion.getRgbBySection

---

README.md

Analyzed and added documentation for the function getMonthDays.

Issue #44: Analyze and document getMonthDays

---

README.md
Sorts/test/InsertionSort.test.js

Added tests for the function insertionSort in Sorts/InsertionSort.js and documented their impact.

Issue #48: Add tests for the function insertionSort in Sorts/InsertionSort.js

---

Maths/test/SimpsonIntegration.test.js
README.md

Added tests to increase coverage to 100%. Also added documentation and a link to the commit where the tests were implemented.

Issue #50: Add tests to increase coverage of the function simpsonIntegration in Maths/SimpsonIntegration.js

---

Graphs/PrimMST.js
Graphs/test/PrimMST.test.js
README.md

Adds a test file and four unit tests for PrimMST and specifically _shiftDown.
Updates the ReadMe to assess work done.

Issue #62: improve branch coverage for `PrimMST.js`

---

README.md

The README file is extended with a short project description together with a link to the original repository.

Issue #70: Adds information to README file

---

README.md

FEAT:
Added documentation of tests and included commits of test implementation

81 add documentation of new implemented test for functions datedaydifferencedatedaydifference and maxproductofthreemaxproductofthree

---

README.md

Refactors the README file in order to remove old template notes, add missing links, adjust some diverging styles and order functions alphabetically.

Issue #73: Refactors the README file

---

README.md

Added documentation for the ad-hoc coverage tool for the function integralEvaluation.

Issue #84: Document the ad-hoc coverage tool for integralEvaluation

---

README.md

Issue87 FEAT: Updated README with documentation of ad-hoc tool for funciton MaxProductOfThree

Issue87 FEAT: Updated README

---

Dynamic-Programming/MaxProductOfThree.js
README.md

Feat: Done with documentation in README

55 analyze the function maxproductofthreemaxproductofthree

---

README.md

FEAT: Done with documentation for analysis of complexity for DateDayDifference

54 analyze the function datedaydifferencedatedaydifference

---

Dynamic-Programming/MaxProductOfThree.js
README.md

FEAT: Refactoring implementation of function MaxProductOfThree function and documentation in README

76 refactor function maxproductofthreemaxproductofthree

---

Dynamic-Programming/MaxProductOfThree.js
Dynamic-Programming/tests/MaxProductOfThree.test.js

FEAT: move tests from branch to main

Issue74 add tests to improve branch coverage of maxproductofthree on main
